import re
import json
import html
from typing import List, Dict, Tuple

_TAG_RE = re.compile(r'<[^>]+>')

HEADING_RE = re.compile(r'^(?:SCENE|SHOT)\s+\d+[:.]?\s*(.*)$', re.IGNORECASE)
ACTION_RE = re.compile(r'^\[ACTION:\s*(.*)\]$', re.IGNORECASE)
CAMERA_RE = re.compile(r'^\[CAMERA:\s*(.*)\]$', re.IGNORECASE)
DIALOGUE_RE = re.compile(r'^\[DIALOGUE:\s*(.*)\]$', re.IGNORECASE)
TRANSITION_RE = re.compile(r'^(CUT TO|FADE IN|FADE OUT|DISSOLVE TO|SMASH CUT)[:.]?\s*$', re.IGNORECASE)
CHARACTER_RE = re.compile(r'^[A-Z][A-Z0-9 \-]{1,30}$')

def _sanitize(text):
    text = html.unescape(text)
    text = _TAG_RE.sub('', text)
    return text

def _ensure(scenes):
    if not scenes:
        scenes.append({'scene_number': 1, 'description': 'Main', 'start_time': 0,
                       'end_time': 0, 'duration': 0, 'blocks': []})
    return scenes[-1]

class ScriptParsingService:
    def __init__(self):
        pass
    
    def parse_script(self, script_text: str) -> Dict:
        """
        Parse the generated script into structured data with separate shots and voiceover.
        
        Args:
            script_text (str): The raw script text generated by the LLM
            
        Returns:
            Dict: Parsed script with title, scenes, shots, and voiceover
        """
        # Extract title with improved regex
        title_match = re.search(r'^\s*\**Title:\s*[""]?([^"\n\*]+)[""]?\**', script_text, re.MULTILINE | re.IGNORECASE)
        title = _sanitize(title_match.group(1).strip()) if title_match else "Untitled Video"
        
        # Extract full narrative if present
        full_narrative_match = re.search(r'\*\*Full Narrative:\*\*\s*(.*?)(?=\n\*\*Scene|\n\*\*$|$)', script_text, re.DOTALL | re.IGNORECASE)
        full_narrative = _sanitize(full_narrative_match.group(1).strip()) if full_narrative_match else ""

        # Prefer screenplay-format parsing when typed blocks are present
        screenplay_scenes = self.parse_screenplay(script_text)
        if screenplay_scenes and any(s.get('blocks') for s in screenplay_scenes):
            return {
                'title': title,
                'full_narrative': full_narrative,
                'scenes': screenplay_scenes
            }
        
        # Extract scenes using a more robust pattern
        scenes = []
        scene_pattern = r'\*\*Scene\s+(\d+):\s*([^(]+)\s*\((\d+)s?-(\d+)s?\)\*\*\s*$(.*?)$\s*Voiceover:\s*[""]?(.*?)(?=[""]?$|$)'
        scene_matches = re.finditer(scene_pattern, script_text, re.MULTILINE | re.DOTALL | re.IGNORECASE)
        
        for match in scene_matches:
            scene_num = int(match.group(1))
            description = _sanitize(match.group(2).strip())
            start_time = int(match.group(3))
            end_time = int(match.group(4))
            visual_description = _sanitize(match.group(5).strip())
            voiceover_text = _sanitize(match.group(6).strip())
            
            scenes.append({
                'scene_number': scene_num,
                'description': description,
                'start_time': start_time,
                'end_time': end_time,
                'duration': end_time - start_time,
                'visual_description': visual_description,
                'voiceover': voiceover_text
            })
        
        # If we couldn't parse with the strict pattern, try a more lenient approach
        if not scenes:
            scenes = self._parse_script_fallback(script_text)
        
        return {
            'title': title,
            'full_narrative': full_narrative,
            'scenes': scenes
        }

    def parse_screenplay(self, script_text: str) -> List[Dict]:
        """
        Parse a screenplay-format script into scenes with typed blocks.

        Block types: heading, action, character, dialogue, transition, camera.
        """
        scenes = []
        cur = None
        cur_character = None
        for raw in script_text.split('\n'):
            line = raw.strip()
            if not line or line == 'END':
                continue
            h = HEADING_RE.match(line)
            if h and (cur is None or cur.get('blocks')):
                cur = {'scene_number': len(scenes) + 1, 'description': h.group(1).strip(),
                       'start_time': 0, 'end_time': 0, 'duration': 0, 'blocks': []}
                cur['blocks'].append({'type': 'heading', 'text': line})
                scenes.append(cur)
                cur_character = None
                continue
            if ACTION_RE.match(line):
                typ, text = 'action', ACTION_RE.match(line).group(1).strip()
            elif CAMERA_RE.match(line):
                typ, text = 'camera', CAMERA_RE.match(line).group(1).strip()
            elif DIALOGUE_RE.match(line):
                typ, text = 'dialogue', DIALOGUE_RE.match(line).group(1).strip()
            else:
                typ, text = None, None
            if typ:
                block = {'type': typ, 'text': text}
                if typ == 'dialogue' and cur_character:
                    block['speaker'] = cur_character
                if cur is None:
                    cur = _ensure(scenes)
                cur['blocks'].append(block)
                continue
            if TRANSITION_RE.match(line):
                _ensure(scenes)['blocks'].append({'type': 'transition', 'text': line})
                continue
            if CHARACTER_RE.match(line) and cur is not None:
                cur_character = line
                cur['blocks'].append({'type': 'character', 'text': line})
                continue
            if cur is not None and cur['blocks']:
                cur['blocks'].append({'type': 'action', 'text': line})
        return scenes

    def parsed_blocks_to_shotspecs(self, scene: dict) -> list["ShotSpec"]:
        """Turn a parsed scene (its 'blocks') into typed ShotSpec[].

        Keeps camera/action blocks typed instead of flattening: a "camera"
        block's text is parsed for scale + move; an "action" block supplies the
        concrete subject. Falls back to deterministic director when blocks are
        absent. This does NOT change parse_screenplay's contract — it adds a
        typed view on top.
        """
        from src.services.cinema.director_service import deterministic_director, keyword_to_scale
        from src.services.cinema.shot import ShotSpec
        from src.services.cinema.types import CameraMove, ShotFunction, ShotScale

        blocks = scene.get("blocks") or []
        camera_text = ""
        action_text = ""
        for b in blocks:
            if b.get("type") == "camera":
                camera_text += " " + b.get("text", "")
            elif b.get("type") == "action":
                action_text += " " + b.get("text", "")
        camera_text = camera_text.strip()
        action_text = action_text.strip()

        if not action_text and not camera_text:
            # fall back so a scene is never empty
            return deterministic_director(
                scene.get("description", ""), scene.get("scene_number") or 1, shot_count_hint=3
            )

        scale = ShotScale.MS
        low_cam = camera_text.lower()
        if "close-up" in low_cam or "close up" in low_cam or "macro" in low_cam:
            scale = ShotScale.CU
        elif "wide" in low_cam or "establish" in low_cam or "aerial" in low_cam:
            scale = ShotScale.ELS
        else:
            scale = keyword_to_scale(action_text)

        move = CameraMove.STATIC
        if "dolly in" in low_cam:
            move = CameraMove.DOLLY_IN
        elif "dolly out" in low_cam:
            move = CameraMove.DOLLY_OUT
        elif "pan" in low_cam:
            move = CameraMove.PAN
        elif "tilt" in low_cam:
            move = CameraMove.TILT
        elif "handheld" in low_cam:
            move = CameraMove.HANDHELD

        return [
            ShotSpec(
                scene_number=scene.get("scene_number") or 1,
                shot_index=0,
                narrative_beats=action_text,
                subject_concrete=action_text if action_text else scene.get("description", ""),
                scale=scale,
                move=move,
                function=ShotFunction.CONTEXT,
                mood="dim",
            )
        ]

    def _parse_script_fallback(self, script_text: str) -> List[Dict]:
        """
        Fallback parsing method for when the strict pattern doesn't match.
        """
        scenes = []
        lines = script_text.split('\n')
        
        current_scene = None
        i = 0
        scene_counter = 1
        
        while i < len(lines):
            line = lines[i].strip()
            
            # Look for scene headers
            scene_match = re.match(r'^\*\*Scene\s+(\d+):\s*([^(\n]+)\s*\((\d+)s?-(\d+)s?\)\*\*(.*)?', line, re.IGNORECASE)
            if scene_match:
                if current_scene:
                    scenes.append(current_scene)
                
                current_scene = {
                    'scene_number': int(scene_match.group(1)),
                    'description': _sanitize(scene_match.group(2).strip()),
                    'start_time': int(scene_match.group(3)),
                    'end_time': int(scene_match.group(4)),
                    'duration': int(scene_match.group(4)) - int(scene_match.group(3)),
                    'visual_description': '',
                    'voiceover': ''
                }
                
                # Look for visual description in the same line or next line
                # Check if there's content after **) in the same line
                same_line_content = scene_match.group(5).strip() if scene_match.group(5) else ''
                if same_line_content.startswith('(') and same_line_content.endswith(')'):
                    current_scene['visual_description'] = _sanitize(same_line_content[1:-1])
                elif i + 1 < len(lines):
                    # Check next line
                    next_line = lines[i + 1].strip()
                    if next_line.startswith('(') and next_line.endswith(')'):
                        current_scene['visual_description'] = _sanitize(next_line[1:-1])
                
                # Look for voiceover in subsequent lines
                j = i + 1
                while j < len(lines):
                    voiceover_line = lines[j].strip()
                    if voiceover_line.lower().startswith('voiceover:'):
                        # Extract the voiceover text
                        voiceover_match = re.match(r'voiceover:\s*["]?([^"\n]*)["]?', voiceover_line, re.IGNORECASE)
                        if voiceover_match:
                            current_scene['voiceover'] = _sanitize(voiceover_match.group(1).strip())
                        break
                    elif voiceover_line.startswith('**Scene') or voiceover_line.startswith('**Title'):
                        break
                    j += 1
                
                i = j + 1 if j > i else i + 1
                scene_counter += 1
            else:
                i += 1
        
        # Add the last scene if it exists
        if current_scene:
            scenes.append(current_scene)
        
        # If still no scenes found, do a very basic parsing
        if not scenes:
            scenes = self._parse_basic_format(script_text)
        
        return scenes
    
    def _parse_basic_format(self, script_text: str) -> List[Dict]:
        """
        Very basic parsing for minimal format.
        """
        # First, try to extract any narrative text
        # Look for a continuous block of text that might be the narrative
        lines = script_text.split('\n')
        narrative_lines = []
        
        for line in lines:
            line = line.strip()
            # Skip lines that look like headers or scene markers
            if not line.startswith('**Scene') and not line.startswith('**Title') and not line.startswith('Voiceover:'):
                # If it's not obviously a marker line, treat as narrative
                if line and len(line) > 10:  # Only consider substantial lines
                    narrative_lines.append(line)
        
        # If we found narrative lines, join them
        if narrative_lines:
            full_narrative = ' '.join(narrative_lines)
        else:
            # Fallback to the entire text
            full_narrative = script_text.strip()
        
        # Extract all voiceover lines
        voiceover_matches = re.findall(r'Voiceover:\s*["]?([^"\n]+)["]?', script_text, re.IGNORECASE)
        
        # If we have a full narrative, use that as the voiceover
        if full_narrative and len(full_narrative) > 50:  # Only if substantial
            return [{
                'scene_number': 1,
                'description': "Main Narrative",
                'start_time': 0,
                'end_time': 30,
                'duration': 30,
                'visual_description': "General visuals for the narrative",
                'voiceover': _sanitize(full_narrative.strip())
            }]
        
        # If we have multiple voiceover segments, try to create a coherent narrative
        if len(voiceover_matches) > 1:
            # For the problematic format, we'll create a more coherent narrative
            # by joining the fragments with appropriate connecting words
            connected_narrative = self._connect_fragments(voiceover_matches)
            return [{
                'scene_number': 1,
                'description': "Coherent Narrative",
                'start_time': 0,
                'end_time': 30,
                'duration': 30,
                'visual_description': "General visuals for the narrative",
                'voiceover': _sanitize(connected_narrative)
            }]
        
        # Create simple scenes for each voiceover
        scenes = []
        num_scenes = max(1, len(voiceover_matches))  # Ensure at least 1 scene
        total_duration = 30  # Default duration
        
        for i, voiceover in enumerate(voiceover_matches):
            # Distribute timing evenly across all scenes
            start_time = int((i / num_scenes) * total_duration)
            end_time = int(((i + 1) / num_scenes) * total_duration)
            
            scenes.append({
                'scene_number': i + 1,
                'description': f"Scene {i + 1}",
                'start_time': start_time,
                'end_time': end_time,
                'duration': end_time - start_time,
                'visual_description': "General visuals for this scene",
                'voiceover': _sanitize(voiceover.strip())
            })
        
        # If no scenes were created, create a single scene for the entire duration
        if not scenes:
            scenes = [{
                'scene_number': 1,
                'description': "Main Scene",
                'start_time': 0,
                'end_time': total_duration,
                'duration': total_duration,
                'visual_description': "General visuals",
                'voiceover': _sanitize(script_text.strip())
            }]
        
        return scenes
    
    def _connect_fragments(self, fragments: List[str]) -> str:
        """
        Connect sentence fragments into a more coherent narrative.
        
        Args:
            fragments (List[str]): List of sentence fragments
            
        Returns:
            str: More coherent narrative
        """
        if not fragments:
            return ""
        
        # If we have a small number of fragments, try to connect them meaningfully
        if len(fragments) <= 5:
            # Simple connection with commas and conjunctions
            if len(fragments) == 1:
                return fragments[0]
            elif len(fragments) == 2:
                return f"{fragments[0]} and {fragments[1]}"
            else:
                # For more fragments, connect with commas and 'and' for the last one
                main_part = ", ".join(fragments[:-1])
                return f"{main_part}, and {fragments[-1]}"
        
        # For many fragments, just join with commas
        return ", ".join(fragments)
    
    def extract_voiceover_text(self, parsed_script: Dict) -> str:
        """
        Extract clean voiceover text for TTS generation.
        
        Args:
            parsed_script (Dict): The parsed script from parse_script()
            
        Returns:
            str: Clean voiceover text
        """
        # Prefer dialogue blocks from screenplay-format scenes
        dialogue_parts = []
        for scene in parsed_script.get('scenes', []):
            for block in scene.get('blocks', []):
                if block.get('type') == 'dialogue' and block.get('text', '').strip():
                    dialogue_parts.append(block['text'].strip())
        if dialogue_parts:
            result = ' '.join(dialogue_parts)
            result = re.sub(r'\s+', ' ', result)
            return _sanitize(result.strip())

        # Fallback to full narrative
        full_narrative = parsed_script.get('full_narrative', '')
        if full_narrative and full_narrative.strip():
            return _sanitize(full_narrative.strip())
        
        # Fallback to concatenating scene voiceovers with proper sentence handling
        voiceover_parts = []
        for scene in parsed_script.get('scenes', []):
            if scene.get('voiceover'):
                voiceover = scene['voiceover'].strip()
                # Only add non-empty voiceovers
                if voiceover:
                    voiceover_parts.append(voiceover)
        
        # Join with spaces and clean up extra whitespace
        result = ' '.join(voiceover_parts)
        # Clean up any extra spaces
        result = re.sub(r'\s+', ' ', result)
        return _sanitize(result.strip())
    
    def extract_shot_descriptions(self, parsed_script: Dict) -> List[str]:
        """
        Extract shot descriptions for stock footage search.
        
        Args:
            parsed_script (Dict): The parsed script from parse_script()
            
        Returns:
            List[str]: List of shot descriptions
        """
        shot_descriptions = []
        for scene in parsed_script.get('scenes', []):
            blocks = scene.get('blocks', [])
            action_camera = [b['text'] for b in blocks
                             if b.get('type') in ('action', 'camera') and b.get('text', '').strip()]
            if action_camera:
                shot_descriptions.extend(_sanitize(text) for text in action_camera)
            elif scene.get('visual_description'):
                shot_descriptions.append(_sanitize(scene['visual_description']))
            # Fallback to general description if no specific visual description
            elif scene.get('description'):
                shot_descriptions.append(_sanitize(scene['description']))
        
        return shot_descriptions

# Global instance
script_parsing_service = ScriptParsingService()